sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ndnNVJu8h2pidyaHMImUYmdghfpGqn9cXBLU1K2/MgSvFTBgD69Vlr+yLPJEgMrplkOc1EdumYzkNR6xdlXUkkCLg9Ac8emjbtby9GsYoKKPNQjfDi19npuUxwn/PbyAcYp/u1sWZDAsI6TVE0i+c7ihe9/PgrM4n7RqDudQktuAARz/amVt1HNiGvaHfh0JJSt2PAXi9dGB2fRsNdItvljIfmgHIHGRB7Atg51HFqnwUX58QGAUPBR1B3p8x6snK6Q23TXf1NMyL0/vEDhhtTq5lxLrrW4Ets7fts2SbJ6dK6LfDVmF+LVBMVrcPNBWIaaefso768yJUJ//dxp+GG6T7scL3N9bJswvR1WWB2dld73OUFkFePliNHWVppRsWhxZe9zVxWr2y/oRrOI/BQpaLZuCheXxkbkZED+80MblMKmxhl2ybmF28Y3yA9iJVDC7VbxRC/ZNNNcpyl4YCKjAZhptnjryEYJDMcxP10mQP/3DKlizUTePptLj9rtJfWEb5CzY1V3/cinwPN6KbOZhBESSKIqBIAMVhxk9jjJxyGNTMODa7GhVZQhp1Os/tUEv/4YLPNabP55nMiQ/jKGByc/lHZVRsTN1NscdfmEJX6fF98HvCDl/sjh/dqXmfhjoQgEj5tJoKvURCTb1aUjrhp5dEUOvv3wY+yy7Jkc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/A-Siren_5179
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy